//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeTrackerManagement.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbltime
    {
        public long IdTrack { get; set; }
        public string Username { get; set; }
        public Nullable<System.DateTime> TimeIn { get; set; }
        public Nullable<System.DateTime> TimeOut { get; set; }
        public Nullable<System.DateTime> DateReference { get; set; }
        public string Status { get; set; }
        public decimal TotalHrs { get; set; }
    }
}
